version: "3.8"

services:
  psql:
    image: postgres:13.1
    depends_on:
      - app
    ports:
      - 5432:5432
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - psql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: joren
      POSTGRES_PASSWORD: pineapples

  app:
    image: jorenb/node-app:latest
    command: sh -c "npm i && tail -F Dockerfile"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      APP_KEY: x4I20cn%0XyUYROxG1smJ*JFhi
      SITE_API_DB_USER: joren
      SITE_API_DB_PW: pineapples

  # during dev, you can run stripe-cli commands in here e.g. to send webhook events
  stripe:
    image: stripe/stripe-cli:latest
    depends_on:
      - app
    command: "listen --forward-to http://host.docker.internal:3000/api/payments/webhook --api-key ${STRIPE_TEST_KEY}"
    environment:
      STRIPE_API_KEY: ${STRIPE_TEST_KEY}

volumes:
  psql-data: