name: Deploy

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy through git pull
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_ADDRESS: ${{ secrets.SSH_ADDRESS }}
        run: |
          ssh "$SSH_USER"@"$SSH_ADDRESS" cd "$SITE_API_DIR"; git pull; npm ci; pm2 restart "site api";